### ISSUE TITLE
편의성 추가 issue

### ISSUE THREAD

**Issue by greeenux** [sejong-infine/freeotp-android#16]
편의성 관련된 issue를 한번 생각해 보았습니다.
만약 사용자가 접근 인증 check 시 , 사용자가 적어도 자신의 인증이 틀렸는지 맞았는지에 관한
메세지 출력을 모르기에, 이런 예시를 들어 보았습니다.  메세지는 영어로 할 예정입니다.

**Comment by greeenux** [comment]
현재 MainActivity파일을 수정하여 pull request를 하였습니다.
사용자의 인증 실패 시, 사용자의 편의성을 위해 필요한 내용이라 생각합니다.

**Comment by cupsos** [comment]
#19
