### ISSUE TITLE
'설정' 창 UI 구현

### ISSUE THREAD

**Issue by cupsos** [sejong-infine/freeotp-android#2]
FreeOTP 에는 '설정' 을 조작할 수 있는 기존 UI가 존재하지 않습니다.

이해를 돕기 위한 디자인 예시. //어디까지나 예시입니다. 실제론 이거보단 나을 겁니다.
┌─────────────────────┐
│                              │
│                              │
│   lock      [disable|enable]    │
│   lock type  [screen|fingerprint] │
│   duration  [10sec|30sec|60sec] │
│                              │
│                              │
│                              │
└─────────────────────┘

- [x] UI 제작
- [ ] #3 으로 UI 활성화
- [ ] 각 옵션 설정이 기능하는지 확인할 수 있는 [로깅](https://developer.android.com/reference/android/util/Log.html) or [토스트](https://developer.android.com/reference/android/widget/Toast.html) 메세지

**Comment by greeenux** [comment]
안드로이드 로그확인하는방법 찾아보겠습니다.

**Comment by ABCorabc** [comment]
팀장님 안드로이드 스튜디오에서 팝업 형식으로 되어있는 이미지가 about.xml 맞는지 알려주시면 감사하겠습니다!
제가 아이폰이다보니 직접 어플을 확인할 수가 없습니다.ㅠ
![image](https://user-images.githubusercontent.com/32122647/33359974-e644d95a-d514-11e7-8243-0f32457e6956.png)

**Comment by cupsos** [comment]
@ABCorabc 
> 팀장님 안드로이드 스튜디오에서 팝업 형식으로 되어있는 이미지가 about.xml 맞는지 알려주시면 감사하겠습니다!
> 제가 아이폰이다보니 직접 어플을 확인할 수가 없습니다.ㅠ
 
엄연히 말하면 이미지가 아니지만, 팝업 형식으로 뜨는 것 맞습니다.
Android Studio 상단 메뉴의 Run 에 [에뮬레이터](https://developer.android.com/studio/run/emulator.html?hl=ko)에서 테스트 할 수 있는 기능이 있으니 그쪽 설정을 먼저 완료해 주세요.

**Comment by cupsos** [comment]
#7
