### ISSUE TITLE
CredentialManager.java의 주석 수정

### ISSUE THREAD

**Issue by cupsos** [sejong-infine/freeotp-android#22]
마지막 pull-request를 하기 전에 CredentialManager.java의 주석을 수정하여야 합니다.

- [x] 불필요한 주석 제거
- [x] 꼭 필요한 주석은 영어로 번역

**Comment by greeenux** [comment]
주석의 수정과 변수의 이해를 위해 수정을 몇가지 하였습니다.
pull request를 통해 확인 부탁드립니다.

**Comment by cupsos** [comment]
#29
