### ISSUE TITLE
SettingActivity에 CredentialManager의 기능을 적용

### ISSUE THREAD

**Issue by cupsos** [sejong-infine/freeotp-android#27]

**Comment by leejunny** [comment]
setting activity 적용 시키겠습니다.

**Comment by leejunny** [comment]
새로운 branch set-settingActivity 생성 하였습니다. 버튼 작업 먼저 하겠습니다.

**Comment by ABCorabc** [comment]
SettingActivity에 각 버튼을 클릭할 때 마다 토스트 메시지를 띄우는 작업 하겠습니다.

**Comment by cupsos** [comment]
지금 작업하는 내용에서 도와드릴 것 있나요?

UI에 문제가 있어서 직접 수정하려는데, 여기 작업과 충돌 날 것 같아서 이거 끝나고 하려구요

**Comment by leejunny** [comment]
끝났습니다! 확인 부탁 드립니다.

**Comment by cupsos** [comment]
#33
