### ISSUE TITLE
'설정' 창을 호출할 버튼을 추가

### ISSUE THREAD

**Issue by cupsos** [sejong-infine/freeotp-android#3]
- [x] Icon 리소스 추가 //저작권 문제 없는 이미지로
- [x] menu에 [MenuItem](https://developer.android.com/reference/android/view/MenuItem.html) 배치

- [x] 기능하는지 확인할 수 있는 [로깅](https://developer.android.com/reference/android/util/Log.html) or [토스트](https://developer.android.com/reference/android/widget/Toast.html) 메세지

![ss](https://user-images.githubusercontent.com/24942851/33355728-06d78e56-d4fc-11e7-9654-015769fe750e.png)

**Comment by cupsos** [comment]
@ehworbs 
완료하셨으면 infine-master로 [pull request](https://github.com/sejong-infine/freeotp-android/compare/sejong-infine:infine-master...develop-menubutton) 부탁드립니다.

**Comment by leejunny** [comment]
main.xml에 switch item 추가 하시고 아이콘 변경 하시면 될 것 같습니다.

**Comment by cupsos** [comment]
#20
