### ISSUE TITLE
SettingActivty 비정상적인 동작

### ISSUE THREAD

**Issue by cupsos** [sejong-infine/freeotp-android#32]
옵션을 설명하는 텍스트가 수정가능한 값입니다.

시간값 설정하는 라디오 버튼 3개가 독립적으로 동작합니다.
바꿔말해서, 10sec, 30sec, 60sec 버튼을 누르면 전부 활성화되고 해제할 수 없습니다.

**Comment by ABCorabc** [comment]
이 사항에 대해서는 라디오버튼 3개를 그룹화해서 수정하겠습니다.

**Comment by ABCorabc** [comment]
옵션을 섦여하는 텍스트 값들을 읽기전용으로 변경했습니다.

**Comment by cupsos** [comment]
#31
