### ISSUE TITLE
인증 상태 및 설정을 저장/로드/기능할 클래스 생성

### ISSUE THREAD

**Issue by cupsos** [sejong-infine/freeotp-android#4]
Default는 사용하지 않음(disable) 이어야 합니다.
설정 적용 여부, 지문인식 여부, 시간 값을 메소드 호출을 통해 수정할 수 있어야 하며, 그 값을 저장하여야 합니다. 앱 실행 시 값을 로드하여야 합니다.
데이터가 단순하므로 [SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences.html) 로 충분할 것 같습니다.

- [x] 클래스 구현
- [x] 앱 실행 시 설정 로드 or 초기화
- [x] OTP 값 노출 시도 시 체크
~~- [ ] #2 에서 호출~~

**Comment by leejunny** [comment]
SharedPreference시 /data/data/"PACKAGE_NAME"/shared_prefs/"PREFS_NAME".xml
에 저장됩니다. 간단한 설정정보를 저장하고 앱 실행시 불러오는데 사용됩니다.

**Comment by cupsos** [comment]
1fbc98ce902f32e0670588d3f206f281e44a34ae
클래스 초안 작성했습니다. 확인해 보세요.

**Comment by leejunny** [comment]
SharedPreference를 이 CredentialManager 클래스 에서 선언 후 사용 해야 하는 것인가요? setting에 reset을 구현하여 초기화 기능을 구현하는 것도 좋을 것 같습니다.

**Comment by cupsos** [comment]
@leejunny 
> SharedPreference를 이 CredentialManager 클래스 에서 선언 후 사용 해야 하는 것인가요?

네 맞습니다.

> setting에 reset을 구현하여 초기화 기능을 구현하는 것도 좋을 것 같습니다.

그것도 좋네요. 필요하다면 메소드 생성해서 구현해주세요

**Comment by leejunny** [comment]
/*
     * 기존 설정을 불러와서 변수에 저장
     * Context : this
     * 설정 1 <LOCK> : default false, 사용 할 경우 true, 안 할경우 : false
     * 설정 2 <FINGER> : default false, 사용할 경우 true, 안 할경우 : false
     * 설정 3 <TIMETYPE> : default 2(Timetype.SEC_60), 0 : 10, 1 : 30, 2 : 60
     */    

private  void loadConfig(Context ct) {
        settingData = ct.getApplicationContext().getSharedPreferences("setting", Context.MODE_PRIVATE);
        mEnable = settingData.getBoolean("LOCK",false);
        if(mEnable == true)
            mUseFingerprint = settingData.getBoolean("FINGER",false);

        mTime = settingData.getInt("TIMETYPE",2);
    }

이런 식으로 코드를 짜고 있는 과정입니다. Context의 개념이 이해가 안가는데 getSharedPreferences를 호출하기 위해서는 Context parameter가 필요 한 것 같은데, 이 부분은 UI에서 Context를 구현하면 되는 것 일까요?

**Comment by cupsos** [comment]
@leejunny 
```java
    private Context mAppContext = null;
//중략
    public int init(Context appContext) {
        mAppContext = appContext;
        if(isConfigExist() && isConfigValid()) {
            loadConfig();
        }
        else {
            saveConfig();
        }
        return 0;
}
```
[mainactivity](https://github.com/sejong-infine/freeotp-android/commit/58684a7d7cb86da1d52464febc236d40230a9b89#diff-b5d9084a2a3de8413a49d7ec80d38cee) 생성 시 init을 호출해서 초기화하고, 이때 Context는 mAppContext에 저장하므로 loadConfig에서 입력을 받을 필요는 없을 것 같네요.  
혹시 branch pull 안하셨나요?

**Comment by leejunny** [comment]
@cupsos 네 아직 안했습니다. 그래서 인지 mainactivity에 mAppContext가 없네요.. 다시 시도해 보도록 하겠습니다

**Comment by cupsos** [comment]
mUseFingerprint 옵션 그냥 뺄까요?  

제가 처음에 잘 몰라서 제안하긴 했는데, [동일 메소드](https://developer.android.com/reference/android/app/KeyguardManager.html#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence))에서 (패턴|PIN|비밀번호)+지문 인증 가능하더라고요.  
권한도 normal이라 사용자 동의 요구하지도 않구요.

**Comment by leejunny** [comment]
@cupsos 
패턴,비밀번호,지문인증이 한가지 method안에서 진행되면 그것도 boolen타입보다는 enum지정해서 3가지 나눠서 구현해도 될것 같네용 어떤 방식으로 인증을 한번 더 진행할 것인지 정하면 될거 같아요. mUseLockType과 같은 형식으로 하면 될 것 같아요.

**Comment by cupsos** [comment]
[3가지](https://developer.android.com/reference/android/app/KeyguardManager.html#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence)) 라는게, 사용자가 기기에 설정한 방식으로 작동하는 것이라 enum으로 하면 안될 것 같습니다.  
[지문만](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html#authenticate(android.hardware.fingerprint.FingerprintManager.CryptoObject,%20android.os.CancellationSignal,%20int,%20android.hardware.fingerprint.FingerprintManager.AuthenticationCallback,%20android.os.Handler)) 쓰는 방식이 있긴 한데, 이걸 적용하는 게 좋을 진 판단이 안서네요.

**Comment by leejunny** [comment]
앗.......... 그러면 다시 돌려놓아야 겠군요 제가 이전버전에 상수 생성한거 해서 다시 commit하겠습니다

**Comment by cupsos** [comment]
네. 해당 작업까지 하시고 pull-request 해주세요.  
이 Issue는 merge 후 Close 하겠습니다.

**Comment by cupsos** [comment]
#10
