### ISSUE TITLE
브랜치 develop-authfunction : 신뢰할 수 없는 시간값을 인증에 사용

### ISSUE THREAD

**Issue by hyunjunmoon** [sejong-infine/freeotp-android#8]
현재 Authfunction 브랜치 merge후에 취약점, 버그, 제안사항 있으면 코멘트, 이슈  작성해 주시면 감사하겠습니다.

지금 팀장님이 말씀해주신 취약점은 마지막 인증후에 앱 종료 안 하고 핸드폰 시간을 과거로 돌리면 인증상태가 초기화가 안되고 계속 인증상태가 유지된다는데 이부분은 제가 한번 수정 해보겠습니다.

다른 불편한 점이나 개선사항 코멘트 해주시기 바랍니다.

**Comment by cupsos** [comment]
제목과 본문만으로는 다른 사람들이 이해하기 힘들 것 같네요.  
해당 취약점 지점 확인 후에 좀더 간결하게 정리하여 필드명과 예시를 들어 코멘트 부탁드립니다.

제목은 제가 수정하겠습니다.

**Comment by hyunjunmoon** [comment]
정리 해서 바로 코멘트 하겠습니다

**Comment by cupsos** [comment]
#28
